% Bulk Concentration
plot(mpb_X, mpb_P_C_0(1, :), '-r', ...
     mpb_X, mpb_P_C_0(2, :), '-g', ... 
     mpb_X, mpb_P_C_0(3, :), '-b', ...
     mpb_X, mpb_P_C_0(4, :), '-c', ...
     mpb_X, mpb_P_C_0(5, :), '-m', ...
     'LineWidth', 2);
 
title({'Potential v. Distance from Interface (MPB)  ',...
    '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance (m)   ', 'FontSize', 24);
ylabel('Potential (V)   ', 'FontSize', 24);
legend('C0 = 0.01 M', 'C0 = 0.05 M', 'CO = 0.10 M', ...
       'C0 = 0.15 M', 'C0 = 0.30 M', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_C_0(1, :) ./ 1000, '-r', ...
%      pb_X, pb_Cneg_C_0(1, :) ./ 1000, '--r', ...
%      pb_X, pb_Cpos_C_0(2, :) ./ 1000, '-g', ...
%      pb_X, pb_Cneg_C_0(2, :) ./ 1000, '--g', ...
%      pb_X, pb_Cpos_C_0(3, :) ./ 1000, '-b', ...
%      pb_X, pb_Cneg_C_0(3, :) ./ 1000, '--b', ...
%      pb_X, pb_Cpos_C_0(4, :) ./ 1000, '-c', ...
%      pb_X, pb_Cneg_C_0(4, :) ./ 1000, '--c', ...
%      pb_X, pb_Cpos_C_0(5, :) ./ 1000, '-m', ...
%      pb_X, pb_Cneg_C_0(5, :) ./ 1000, '--m', 'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (PB)   ', ...
%     '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('C0 = 0.01 M (z = +1)', 'C0 = 0.01 M (z = -1)', ...
%        'C0 = 0.05 M (z = +1)', 'C0 = 0.05 M (z = -1)', ...
%        'C0 = 0.10 M (z = +1)', 'CO = 0.10 M (z = -1)', ...
%        'C0 = 0.15 M (z = +1)', 'C0 = 0.15 M (z = -1)', ...
%        'C0 = 0.30 M (z = +1)', 'C0 = 0.30 M (z = -1)');
% 
% subplot(2, 1, 2);
plot(mpb_X, mpb_Cpos_C_0(1, :) ./ 1000, '-r', ...
     mpb_X, mpb_Cneg_C_0(1, :) ./ 1000, '--r', ...
     mpb_X, mpb_Cpos_C_0(2, :) ./ 1000, '-g', ...
     mpb_X, mpb_Cneg_C_0(2, :) ./ 1000, '--g', ...
     mpb_X, mpb_Cpos_C_0(3, :) ./ 1000, '-b', ...
     mpb_X, mpb_Cneg_C_0(3, :) ./ 1000, '--b', ...
     mpb_X, mpb_Cpos_C_0(4, :) ./ 1000, '-c', ...
     mpb_X, mpb_Cneg_C_0(4, :) ./ 1000, '--c', ...
     mpb_X, mpb_Cpos_C_0(5, :) ./ 1000, '-m', ...
     mpb_X, mpb_Cneg_C_0(5, :) ./ 1000, '--m', 'LineWidth', 2);
 
title({'Ion Concentration v. Distance from Interface (MPB)   ', ...
    '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance(m)   ', 'FontSize', 24);
ylabel('Ion Concentration (M)   ', 'FontSize', 24);
legend('C0 = 0.01 M (z = +1)', 'C0 = 0.01 M (z = -1)', ...
       'C0 = 0.05 M (z = +1)', 'C0 = 0.05 M (z = -1)', ...
       'C0 = 0.10 M (z = +1)', 'CO = 0.10 M (z = -1)', ...
       'C0 = 0.15 M (z = +1)', 'C0 = 0.15 M (z = -1)', ...
       'C0 = 0.30 M (z = +1)', 'C0 = 0.30 M (z = -1)', ...
       'FontSize', 16);
set(gca, 'FontSize', 24);
pause;
   
% Permittivity 
plot(mpb_X, mpb_P_E_R(1, :), '-r', ...
     mpb_X, mpb_P_E_R(2, :), '-g', ...
     mpb_X, mpb_P_E_R(3, :), '-b', ...
     mpb_X, mpb_P_E_R(4, :), '-c', ...
     mpb_X, mpb_P_E_R(5, :), '-m', ...
     'LineWidth', 2);
 
title({'Potential v. Distance from Interface (MPB) ',...
    '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance (m)   ', 'FontSize', 24);
ylabel('Potential (V)   ', 'FontSize', 24);
legend('er = 30', 'er = 50', 'er = 78.3', 'er = 100', 'er = 120', ...
       'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_E_R(1, :) ./ 1000, '-r', ...
%      pb_X, pb_Cneg_E_R(1, :) ./ 1000, '--r', ...
%      pb_X, pb_Cpos_E_R(2, :) ./ 1000, '-g', ...
%      pb_X, pb_Cneg_E_R(2, :) ./ 1000, '--g', ...
%      pb_X, pb_Cpos_E_R(3, :) ./ 1000, '-b', ...
%      pb_X, pb_Cneg_E_R(3, :) ./ 1000, '--b', ...
%      pb_X, pb_Cpos_E_R(4, :) ./ 1000, '-c', ...
%      pb_X, pb_Cneg_E_R(4, :) ./ 1000, '--c', ...
%      pb_X, pb_Cpos_E_R(5, :) ./ 1000, '-m', ...
%      pb_X, pb_Cneg_E_R(5, :) ./ 1000, '--m', ...
%       'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (PB)   ', ...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('er = 30 (z = +1)', 'er = 30 (z = -1)', 'er = 50 (z = +1)', ...
%        'er = 50 (z = -1)', 'er = 78.3 (z = +1)', 'er = 78.3 (z = -1)', ...
%        'er = 100 (z = +1)', 'er = 100 (z = -1)', 'er = 120 (z = +1)', ...
%        'er = 120 (z = -1)');
%    
% 
% subplot(2, 1, 2);

plot(mpb_X, mpb_Cpos_E_R(1, :) ./ 1000, '-r', ...
     mpb_X, mpb_Cneg_E_R(1, :) ./ 1000, '--r', ...
     mpb_X, mpb_Cpos_E_R(2, :) ./ 1000, '-g', ...
     mpb_X, mpb_Cneg_E_R(2, :) ./ 1000, '--g', ...
     mpb_X, mpb_Cpos_E_R(3, :) ./ 1000, '-b', ...
     mpb_X, mpb_Cneg_E_R(3, :) ./ 1000, '--b', ...
     mpb_X, mpb_Cpos_E_R(4, :) ./ 1000, '-c', ...
     mpb_X, mpb_Cneg_E_R(4, :) ./ 1000, '--c', ...
     mpb_X, mpb_Cpos_E_R(5, :) ./ 1000, '-m', ...
     mpb_X, mpb_Cneg_E_R(5, :) ./ 1000, '--m', ...
     'LineWidth', 2);
 
title({'Ion Concentration v. Distance from Interface (MPB)   ', ...
    '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance(m)   ', 'FontSize', 24);
ylabel('Ion Concentration (M)   ', 'FontSize', 24);
legend('er = 30 (z = +1)', 'er = 30 (z = -1)', 'er = 50 (z = +1)', ...
       'er = 50 (z = -1)', 'er = 78.3 (z = +1)', 'er = 78.3 (z = -1)', ...
       'er = 100 (z = +1)', 'er = 100 (z = -1)', 'er = 120 (z = +1)', ...
       'er = 120 (z = -1)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;
   
% Ion Size 
plot(mpb_X, mpb_P_EFF(1, :), '-r', ...
     mpb_X, mpb_P_EFF(2, :), '-g', mpb_X, mpb_P_EFF(3, :), '-b', ...
     mpb_X, mpb_P_EFF(4, :), '-c', mpb_X, mpb_P_EFF(5, :), '-m', ...
     'LineWidth', 2);
 
title({'Potential v. Distance from Interface (MPB) ',...
    '(z = 1, C0 = 0.15 M, P0 = 25 mV, er = 78.3)   '}, 'FontSize', 24);
xlabel('Distance (m)   ', 'FontSize', 24);
ylabel('Potential (V)   ', 'FontSize', 24);
legend('ion size = 0.1 nm', 'ion size = 0.5 nm', ...
       'ion size = 1.0 nm', 'ion size = 3.0 nm', ...
       'ion size = 5.0 nm', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;


plot(mpb_X, mpb_Cpos_EFF(1, :) ./ 1000, '-r', ...
     mpb_X, mpb_Cneg_EFF(1, :) ./ 1000, '--r', ...
     mpb_X, mpb_Cpos_EFF(2, :) ./ 1000, '-g', ...
     mpb_X, mpb_Cneg_EFF(2, :) ./ 1000, '--g', ...
     mpb_X, mpb_Cpos_EFF(3, :) ./ 1000, '-b', ...
     mpb_X, mpb_Cneg_EFF(3, :) ./ 1000, '--b', ...
     mpb_X, mpb_Cpos_EFF(4, :) ./ 1000, '-c', ...
     mpb_X, mpb_Cneg_EFF(4, :) ./ 1000, '--c', ...
     mpb_X, mpb_Cpos_EFF(5, :) ./ 1000, '-m', ...
     mpb_X, mpb_Cneg_EFF(5, :) ./ 1000, '--m', ...
     'LineWidth', 2);
 
title({'Ion Concentration v. Distance from Interface (MPB)   ', ...
    '(z = 1, C0 = 0.15 M, P0 = 25 mV, er = 78.3)   '}, 'FontSize', 24);
xlabel('Distance(m)   ', 'FontSize', 24);
ylabel('Ion Concentration (M)   ', 'FontSize', 24);
legend('ion size = 0.1 nm (z = +1)', ...
    'ion size = 0.1 nm (z = -1)', 'ion size = 0.5 nm (z = +1)', ...
    'ion size = 0.5 nm (z = -1)', 'ion size = 1.0 nm (z = +1)', ...
    'ion size = 1.0 nm (z = -1)', 'ion size = 3.0 nm (z = +1)', ...
    'ion size = 3.0 nm (z = -1)', 'ion size = 5.0 nm (z = +1)', ...
    'ion size = 5.0 nm (z = -1)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

% Valence

plot(mpb_X, mpb_P_Z1, '-r', ...
     mpb_X, mpb_P_Z2, '-b', 'LineWidth', 2);
title({'Potential v. Distance from Interface (MPB) ',...
    '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance (m)   ', 'FontSize', 24);
ylabel('Potential (V)   ', 'FontSize', 24);
legend('z = +/- 1', 'z = +/- 2', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_Z1 ./ 1000, '-r', pb_X, pb_Cneg_Z1 ./ 1000, '--r', ...
%      pb_X, pb_Cpos_Z2 ./ 1000, '-b', pb_X, pb_Cneg_Z2 ./ 1000, '--b');
% title(['Ion Concentration v. Distance from Interface (PB)  ',...
%     '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('z = +1', 'z = -1', 'z = +2', 'z = -2');
% 
% subplot(2, 1, 2);
plot(mpb_X, mpb_Cpos_Z1 ./ 1000, '-r', mpb_X, mpb_Cneg_Z1 ./ 1000, '--r', ...
     mpb_X, mpb_Cpos_Z2 ./ 1000, '-b', mpb_X, mpb_Cneg_Z2 ./ 1000, '--b', ...
     'LineWidth', 2);
title({'Ion Concentration v. Distance from Interface (MPB)  ',...
    '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('Distance (m)   ', 'FontSize', 24);
ylabel('Ion Concentration (M)   ', 'FontSize', 24);
legend('z = +1', 'z = -1', 'z = +2', 'z = -2', 'FontSize', 16);
set(gca, 'FontSize', 24);