% GRAPH_CHARGE_CAP.M
% Plot results from CALC_CHARGE_CAP.

% Michelle Shu | June 23, 2013

% -------------------------------------------------------------------------
% A. Bulk Concentration

semilogy(P0_values, pb_Qt_C_0(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_Qt_C_0(1, :) ./ 1e4, '-r', ...
         P0_values, pb_Qt_C_0(2, :) ./ 1e4, '--g', ...
         P0_values, mpb_Qt_C_0(2, :) ./ 1e4, '-g', ...
         P0_values, pb_Qt_C_0(3, :) ./ 1e4, '--b', ...
         P0_values, mpb_Qt_C_0(3, :) ./ 1e4, '-b', ...
         P0_values, pb_Qt_C_0(4, :) ./ 1e4, '--c', ...
         P0_values, mpb_Qt_C_0(4, :) ./ 1e4, '-c', ...
         P0_values, pb_Qt_C_0(5, :) ./ 1e4, '--m', ...
         P0_values, mpb_Qt_C_0(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);
title({'Total Charge per Area v. Applied Voltage (P0)  ', ...
    '(z = 1, er = 78.3, ion size = 1 nm)  '}, 'FontSize', 24);
xlabel('P0 (V)  ', 'FontSize', 24);
ylabel('Charge per Area (C / cm^2)  ', 'FontSize', 24);
legend('C0 = 0.01 M (PB)', 'C0 = 0.01 M (MPB)', 'C0 = 0.05 M (PB)', ...
       'C0 = 0.05 M (MPB)', 'C0 = 0.10 M (PB)', 'C0 = 0.10 M (MPB)', ...
       'C0 = 0.15 M (PB)', 'C0 = 0.15 M (MPB)', 'C0 = 0.30 M (PB)', ...
       'C0 = 0.30 M (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values, pb_C_C_0(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_C_C_0(1, :) ./ 1e4, '-r', ...
         P0_values, pb_C_C_0(2, :) ./ 1e4, '--g', ...
         P0_values, mpb_C_C_0(2, :) ./ 1e4, '-g', ...
         P0_values, pb_C_C_0(3, :) ./ 1e4, '--b', ...
         P0_values, mpb_C_C_0(3, :) ./ 1e4, '-b', ...
         P0_values, pb_C_C_0(4, :) ./ 1e4, '--c', ...
         P0_values, mpb_C_C_0(4, :) ./ 1e4, '-c', ...
         P0_values, pb_C_C_0(5, :) ./ 1e4, '--m', ...
         P0_values, mpb_C_C_0(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);

title({'Capacitance per Area v. Applied Potential (P0) ',...
    '(z = 1, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Capacitance per Area (F / cm^2)   ', 'FontSize', 24);
legend('C0 = 0.01 M (PB)', 'C0 = 0.01 M (MPB)', 'C0 = 0.05 M (PB)', ...
       'C0 = 0.05 M (MPB)', 'C0 = 0.10 M (PB)', 'C0 = 0.10 M (MPB)', ...
       'C0 = 0.15 M (PB)', 'C0 = 0.15 M (MPB)', 'C0 = 0.30 M (PB)', ...
       'C0 = 0.30 M (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values(1, 2 : end), pb_Cdiff_C_0(1, 2 : end) ./ 1e4, '--r', ...
         P0_values(1, 2 : end), mpb_Cdiff_C_0(1, 2 : end) ./ 1e4, '-r', ...
         P0_values(1, 2 : end), pb_Cdiff_C_0(2, 2 : end) ./ 1e4, '--g', ...
         P0_values(1, 2 : end), mpb_Cdiff_C_0(2, 2 : end) ./ 1e4, '-g', ...
         P0_values(1, 2 : end), pb_Cdiff_C_0(3, 2 : end) ./ 1e4, '--b', ...
         P0_values(1, 2 : end), mpb_Cdiff_C_0(3, 2 : end) ./ 1e4, '-b', ...
         P0_values(1, 2 : end), pb_Cdiff_C_0(4, 2 : end) ./ 1e4, '--c', ...
         P0_values(1, 2 : end), mpb_Cdiff_C_0(4, 2 : end) ./ 1e4, '-c', ...
         P0_values(1, 2 : end), pb_Cdiff_C_0(5, 2 : end) ./ 1e4, '--m', ...
         P0_values(1, 2 : end), mpb_Cdiff_C_0(5, 2 : end) ./ 1e4, '-m', ...
         'LineWidth', 2);
        
title({'Differential Capacitance per Area v. Applied Potential (P0) ',...
    '(z = 1, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Differential Capacitance (F / cm ^2)   ', 'FontSize', 24);
legend('C0 = 0.01 M (PB)', 'C0 = 0.01 M (MPB)', 'C0 = 0.05 M (PB)', ...
       'C0 = 0.05 M (MPB)', 'C0 = 0.10 M (PB)', 'C0 = 0.10 M (MPB)', ...
       'C0 = 0.15 M (PB)', 'C0 = 0.15 M (MPB)', 'C0 = 0.30 M (PB)', ...
       'C0 = 0.30 M (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);
   
pause;

% -------------------------------------------------------------------------
% B. Relative Permittivity

semilogy(P0_values, pb_Qt_E_R(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_Qt_E_R(1, :) ./ 1e4, '-r', ...
         P0_values, pb_Qt_E_R(2, :) ./ 1e4, '--g', ...
         P0_values, mpb_Qt_E_R(2, :) ./ 1e4, '-g', ...
         P0_values, pb_Qt_E_R(3, :) ./ 1e4, '--b', ...
         P0_values, mpb_Qt_E_R(3, :) ./ 1e4, '-b', ...
         P0_values, pb_Qt_E_R(4, :) ./ 1e4, '--c', ...
         P0_values, mpb_Qt_E_R(4, :) ./ 1e4, '-c', ...
         P0_values, pb_Qt_E_R(5, :) ./ 1e4, '--m', ...
         P0_values, mpb_Qt_E_R(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);
title({'Total Charge per Area v. Applied Voltage (P0) ',...
    ' (z = 1, C0 = 0.15 M, ion size = 1 nm)  '}, 'FontSize', 24);
xlabel('P0 (V)  ', 'FontSize', 24);
ylabel('Charge per Area (C / cm^2)  ', 'FontSize', 24);
legend('er = 30 (PB)', 'er = 30 (MPB)', 'er = 50 (PB)', 'er = 50 (MPB)',...
       'er = 78.3 (PB)', 'er = 78.3 (MPB)', 'er = 100 (PB)',...
       'er = 100 (MPB)', 'er = 120 (PB)', 'er = 120 (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values, pb_C_E_R(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_C_E_R(1, :) ./ 1e4, '-r', ...
         P0_values, pb_C_E_R(2, :) ./ 1e4, '--g', ...
         P0_values, mpb_C_E_R(2, :) ./ 1e4, '-g', ...
         P0_values, pb_C_E_R(3, :) ./ 1e4, '--b', ...
         P0_values, mpb_C_E_R(3, :) ./ 1e4, '-b', ...
         P0_values, pb_C_E_R(4, :) ./ 1e4, '--c', ...
         P0_values, mpb_C_E_R(4, :) ./ 1e4, '-c', ...
         P0_values, pb_C_E_R(5, :) ./ 1e4, '--m', ...
         P0_values, mpb_C_E_R(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);
     
title({'Capacitance per Area v. Applied Potential (P0) ',...
    '(z = 1, C0 = 0.15 M, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Capacitance per Area (F / cm^2)   ', 'FontSize', 24);
legend('er = 30 (PB)', 'er = 30 (MPB)', 'er = 50 (PB)', 'er = 50 (MPB)',...
       'er = 78.3 (PB)', 'er = 78.3 (MPB)', 'er = 100 (PB)',...
       'er = 100 (MPB)', 'er = 120 (PB)', 'er = 120 (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values(1, 2 : end), pb_Cdiff_E_R(1, 2 : end) ./ 1e4, '--r', ...
         P0_values(1, 2 : end), mpb_Cdiff_E_R(1, 2 : end) ./ 1e4, '-r', ...
         P0_values(1, 2 : end), pb_Cdiff_E_R(2, 2 : end) ./ 1e4, '--g', ...
         P0_values(1, 2 : end), mpb_Cdiff_E_R(2, 2 : end) ./ 1e4, '-g', ...
         P0_values(1, 2 : end), pb_Cdiff_E_R(3, 2 : end) ./ 1e4, '--b', ...
         P0_values(1, 2 : end), mpb_Cdiff_E_R(3, 2 : end) ./ 1e4, '-b', ...
         P0_values(1, 2 : end), pb_Cdiff_E_R(4, 2 : end) ./ 1e4, '--c', ...
         P0_values(1, 2 : end), mpb_Cdiff_E_R(4, 2 : end) ./ 1e4, '-c', ...
         P0_values(1, 2 : end), pb_Cdiff_E_R(5, 2 : end) ./ 1e4, '--m', ...
         P0_values(1, 2 : end), mpb_Cdiff_E_R(5, 2 : end) ./ 1e4, '-m', ...
         'LineWidth', 2);
        
title({'Differential Capacitance per Area v. Applied Potential (P0) ',...
    '(z = 1, C0 = 0.15 M, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Differential Capacitance (F / cm ^2)   ', 'FontSize', 24);
legend('er = 30 (PB)', 'er = 30 (MPB)', 'er = 50 (PB)', 'er = 50 (MPB)',...
       'er = 78.3 (PB)', 'er = 78.3 (MPB)', 'er = 100 (PB)',...
       'er = 100 (MPB)', 'er = 120 (PB)', 'er = 120 (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);
   
pause;

% -------------------------------------------------------------------------
% C. Effective Ion Size

semilogy(P0_values, pb_Qt_EFF(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_Qt_EFF(1, :) ./ 1e4, '-r', ...
         P0_values, mpb_Qt_EFF(2, :) ./ 1e4, '-g', ...
         P0_values, mpb_Qt_EFF(3, :) ./ 1e4, '-b', ...
         P0_values, mpb_Qt_EFF(4, :) ./ 1e4, '-c', ...
         P0_values, mpb_Qt_EFF(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);
title({'Total Charge per Area v. Applied Voltage (P0)',...
    ' (z = 1, C0 = 0.15 M, er = 78.3)'}, 'FontSize', 24);
xlabel('P0 (V)', 'FontSize', 24);
ylabel('Charge per Area (C / cm^2)', 'FontSize', 24);
legend('PB', 'ion size = 0.1 nm (MPB)', 'ion size = 0.5 nm (MPB)', ...
    'ion size = 1.0 nm (MPB)', 'ion size = 3.0 nm (MPB)', ...
    'ion size = 5.0 nm (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values, pb_C_EFF(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_C_EFF(1, :) ./ 1e4, '-r', ...
         P0_values, mpb_C_EFF(2, :) ./ 1e4, '-g', ...
         P0_values, mpb_C_EFF(3, :) ./ 1e4, '-b', ...
         P0_values, mpb_C_EFF(4, :) ./ 1e4, '-c', ...
         P0_values, mpb_C_EFF(5, :) ./ 1e4, '-m', ...
         'LineWidth', 2);
title({'Capacitance per Area v. Applied Potential (P0)',...
    '(z = 1, C0 = 0.15 M, er = 78.3)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Capacitance per Area (F / cm^2)   ', 'FontSize', 24);
legend('PB', 'ion size = 0.1 nm (MPB)', 'ion size = 0.5 nm (MPB)', ...
    'ion size = 1.0 nm (MPB)', 'ion size = 3.0 nm (MPB)', ...
    'ion size = 5.0 nm (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values(1, 2 : end), pb_Cdiff_EFF(1, 2 : end) ./ 1e4, '--r', ...
         P0_values(1, 2 : end), mpb_Cdiff_EFF(1, 2 : end) ./ 1e4, '-r', ...
         P0_values(1, 2 : end), mpb_Cdiff_EFF(2, 2 : end) ./ 1e4, '-g', ...
         P0_values(1, 2 : end), mpb_Cdiff_EFF(3, 2 : end) ./ 1e4, '-b', ...
         P0_values(1, 2 : end), mpb_Cdiff_EFF(4, 2 : end) ./ 1e4, '-c', ...
         P0_values(1, 2 : end), mpb_Cdiff_EFF(5, 2 : end) ./ 1e4, '-m', ...
         'LineWidth', 2);
        
title({'Differential Capacitance per Area v. Applied Potential (P0)',...
    '(z = 1, C0 = 0.15 M, er = 78.3)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Differential Capacitance (F / cm ^2)   ', 'FontSize', 24);
legend('PB', 'ion size = 0.1 nm (MPB)', 'ion size = 0.5 nm (MPB)', ...
    'ion size = 1.0 nm (MPB)', 'ion size = 3.0 nm (MPB)', ...
    'ion size = 5.0 nm (MPB)', 'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

% -------------------------------------------------------------------------
% D. Valence

semilogy(P0_values, pb_Qt_Z(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_Qt_Z(1, :) ./ 1e4, '-r', ...
         P0_values, pb_Qt_Z(2, :) ./ 1e4, '--b', ...
         P0_values, mpb_Qt_Z(2, :) ./ 1e4, '-b', ...
         'LineWidth', 2);
title({'Total Charge per Area v. Applied Voltage (P0) ',...
    '(C0 = 0.15 M, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Charge per Area (C / cm^2)   ', 'FontSize', 24);
legend('Z = 1 (PB)', 'Z = 1 (MPB)', 'Z = 2 (PB)', 'Z = 2 (MPB)', ...
    'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values, pb_C_Z(1, :) ./ 1e4, '--r', ...
         P0_values, mpb_C_Z(1, :) ./ 1e4, '-r', ...
         P0_values, pb_C_Z(2, :) ./ 1e4, '--b', ...
         P0_values, mpb_C_Z(2, :) ./ 1e4, '-b', ...
         'LineWidth', 2);
title({'Capacitance per Area v. Applied Potential (P0) ',...
    '(C0 = 0.15 M, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Capacitance per Area (F / cm^2)   ', 'FontSize', 24);
legend('Z = 1 (PB)', 'Z = 1 (MPB)', 'Z = 2 (PB)', 'Z = 2 (MPB)', ...
    'FontSize', 16);
set(gca, 'FontSize', 24);

pause;

semilogy(P0_values(1, 2 : end), pb_Cdiff_Z(1, 2 : end) ./ 1e4, '--r', ...
         P0_values(1, 2 : end), mpb_Cdiff_Z(1, 2 : end) ./ 1e4, '-r', ...
         P0_values(1, 2 : end), pb_Cdiff_Z(2, 2 : end) ./ 1e4, '--b', ...
         P0_values(1, 2 : end), mpb_Cdiff_Z(2, 2 : end) ./ 1e4, '-b', ...
         'LineWidth', 2);
        
title({'Differential Capacitance per Area v. Applied Potential (P0) ',...
    '(C0 = 0.15 M, er = 78.3, ion size = 1 nm)   '}, 'FontSize', 24);
xlabel('P0 (V)   ', 'FontSize', 24);
ylabel('Differential Capacitance (F / cm ^2)   ', 'FontSize', 24);
legend('Z = 1 (PB)', 'Z = 1 (MPB)', 'Z = 2 (PB)', 'Z = 2 (MPB)', ...
    'FontSize', 16);
set(gca, 'FontSize', 24);