% MPB_POTENTIAL_CONC_PARAMS Script
% Modified Poisson Boltzmann Model
% Display how electric potential profile and ion concentration distribution
% varies with: 
% bulk concentration (0.01 - 0.3 M), relative permittivity (30 - 120),
% effective ion size (0.1 - 5 nm), valence (+/- 1 or +/- 2)

% Michelle Shu | June 25, 2013

% Constants
K = 1.3806488e-23;      % Boltzmann constant (J/K)
T = 293;                % Temperature (K)
E = 1.60217657e-19;     % Elementary charge (C)
N_A = 6.0221413e23;     % Avogadro's number (1/mol)

% Defaults
P_0 = 0.025;            % Applied potential
C_0 = 150;
E_R = 78.3;
EFF = 1e-9;
Z = 1;

% Options for parameter variance
C_0_options = [10 50 100 150 300]; % in mol/m^3 = M * 1e3
E_R_options = [30 50 78.3 100 120];
EFF_options = [1e-10 5e-10 1e-9 3e-9 5e-9];
Z_options = [1 2];

%-------------------------------------------------------------------------
% A. Bulk Concentration

% pb_P_C_0 = zeros(numel(C_0_options), 301);
% pb_Cpos_C_0 = zeros(numel(C_0_options), 301);
% pb_Cneg_C_0 = zeros(numel(C_0_options), 301);
% mpb_P_C_0 = zeros(numel(C_0_options), 301);
% mpb_Cpos_C_0 = zeros(numel(C_0_options), 301);
% mpb_Cneg_C_0 = zeros(numel(C_0_options), 301);

% for i = 1 : numel(C_0_options)
%     [pb_X, pb_P_C_0(i, :), ~] = pb_potential(P_0, C_0_options(i), E_R, Z);
%     pb_Cpos_C_0(i, :) = (C_0_options(i) .* (exp((- E / (K * T)) .* ...
%         pb_P_C_0(i, :))));
%     pb_Cneg_C_0(i, :) = (C_0_options(i) .* (exp((E / (K * T)) .* ...
%         pb_P_C_0(i, :))));
%     
%     [mpb_X, mpb_P_C_0(i, :), ~] = mpb_potential(P_0, C_0_options(i), ...
%         E_R, EFF, Z);
%     mpb_Cpos_C_0(i, :) = (C_0_options(i) .* (exp((- E / (K * T)) .* ...
%         mpb_P_C_0(i, :))));
%     mpb_Cneg_C_0(i, :) = (C_0_options(i) .* (exp((E / (K * T)) .* ...
%         mpb_P_C_0(i, :))));
% end

% Bulk Concentration | Potential
% plot(pb_X, pb_P_C_0(1, :), '--r', mpb_X, mpb_P_C_0(1, :), '-r', ...
%      pb_X, pb_P_C_0(2, :), '--g', mpb_X, mpb_P_C_0(2, :), '-g', ... 
%      pb_X, pb_P_C_0(3, :), '--b', mpb_X, mpb_P_C_0(3, :), '-b', ...
%      pb_X, pb_P_C_0(4, :), '--c', mpb_X, mpb_P_C_0(4, :), '-c', ...
%      pb_X, pb_P_C_0(5, :), '--m', mpb_X, mpb_P_C_0(5, :), '-m', ...
%      'LineWidth', 2);
%  
% title(['Potential v. Distance from Interface  ',...
%     '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Potential (V)   ', 'FontSize', 16);
% legend('C0 = 0.01 M (PB)', 'C0 = 0.01 M (MPB)', 'C0 = 0.05 M (PB)', ...
%        'C0 = 0.05 M (MPB)', 'C0 = 0.10 M (PB)', 'CO = 0.10 M (MPB)', ...
%        'C0 = 0.15 M (PB)', 'C0 = 0.15 M (MPB)', 'C0 = 0.30 M (PB)', ...
%        'C0 = 0.30 M (MPB)');
% 
% pause;

% Bulk Concentration | Ion Concentration

% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_C_0(1, :) ./ 1000, '-r', ...
%      pb_X, pb_Cneg_C_0(1, :) ./ 1000, '--r', ...
%      pb_X, pb_Cpos_C_0(2, :) ./ 1000, '-g', ...
%      pb_X, pb_Cneg_C_0(2, :) ./ 1000, '--g', ...
%      pb_X, pb_Cpos_C_0(3, :) ./ 1000, '-b', ...
%      pb_X, pb_Cneg_C_0(3, :) ./ 1000, '--b', ...
%      pb_X, pb_Cpos_C_0(4, :) ./ 1000, '-c', ...
%      pb_X, pb_Cneg_C_0(4, :) ./ 1000, '--c', ...
%      pb_X, pb_Cpos_C_0(5, :) ./ 1000, '-m', ...
%      pb_X, pb_Cneg_C_0(5, :) ./ 1000, '--m', 'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (PB)   ', ...
%     '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('C0 = 0.01 M (z = +1)', 'C0 = 0.01 M (z = -1)', ...
%        'C0 = 0.05 M (z = +1)', 'C0 = 0.05 M (z = -1)', ...
%        'C0 = 0.10 M (z = +1)', 'CO = 0.10 M (z = -1)', ...
%        'C0 = 0.15 M (z = +1)', 'C0 = 0.15 M (z = -1)', ...
%        'C0 = 0.30 M (z = +1)', 'C0 = 0.30 M (z = -1)');
% 
% subplot(2, 1, 2);
% plot(mpb_X, mpb_Cpos_C_0(1, :) ./ 1000, '-r', ...
%      mpb_X, mpb_Cneg_C_0(1, :) ./ 1000, '--r', ...
%      mpb_X, mpb_Cpos_C_0(2, :) ./ 1000, '-g', ...
%      mpb_X, mpb_Cneg_C_0(2, :) ./ 1000, '--g', ...
%      mpb_X, mpb_Cpos_C_0(3, :) ./ 1000, '-b', ...
%      mpb_X, mpb_Cneg_C_0(3, :) ./ 1000, '--b', ...
%      mpb_X, mpb_Cpos_C_0(4, :) ./ 1000, '-c', ...
%      mpb_X, mpb_Cneg_C_0(4, :) ./ 1000, '--c', ...
%      mpb_X, mpb_Cpos_C_0(5, :) ./ 1000, '-m', ...
%      mpb_X, mpb_Cneg_C_0(5, :) ./ 1000, '--m', 'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (MPB)   ', ...
%     '(z = 1, P0 = 25 mV, er = 78.3, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('C0 = 0.01 M (z = +1)', 'C0 = 0.01 M (z = -1)', ...
%        'C0 = 0.05 M (z = +1)', 'C0 = 0.05 M (z = -1)', ...
%        'C0 = 0.10 M (z = +1)', 'CO = 0.10 M (z = -1)', ...
%        'C0 = 0.15 M (z = +1)', 'C0 = 0.15 M (z = -1)', ...
%        'C0 = 0.30 M (z = +1)', 'C0 = 0.30 M (z = -1)');

% % ------------------------------------------------------------------------
% % B. Permittivity
% 
% pb_P_E_R = zeros(numel(E_R_options), 301);
% pb_Cpos_E_R = zeros(numel(E_R_options), 301);
% pb_Cneg_E_R = zeros(numel(E_R_options), 301);
% mpb_P_E_R = zeros(numel(E_R_options), 301);
% mpb_Cpos_E_R = zeros(numel(E_R_options), 301);
% mpb_Cneg_E_R = zeros(numel(E_R_options), 301);
% 
% for i = 1 : numel(E_R_options)
%     [pb_X, pb_P_E_R(i, :), ~] = pb_potential(P_0, C_0, E_R_options(i), Z);
%     pb_Cpos_E_R(i, :) = (C_0 .* (exp((- E / (K * T)) .* pb_P_E_R(i, :))));
%     pb_Cneg_E_R(i, :) = (C_0 .* (exp((E / (K * T)) .* pb_P_E_R(i, :))));
%     
%     [mpb_X, mpb_P_E_R(i, :), ~] = mpb_potential(P_0, C_0, ...
%         E_R_options(i), EFF, Z);
%     mpb_Cpos_E_R(i, :) = (C_0 .* (exp((- E / (K * T)) .* mpb_P_E_R(i, :))));
%     mpb_Cneg_E_R(i, :) = (C_0 .* (exp((E / (K * T)) .* mpb_P_E_R(i, :))));
% end
% 
% % Permittivity | Potential
% plot(pb_X, pb_P_E_R(1, :), '--r', mpb_X, mpb_P_E_R(1, :), '-r', ...
%      pb_X, pb_P_E_R(2, :), '--g', mpb_X, mpb_P_E_R(2, :), '-g', ...
%      pb_X, pb_P_E_R(3, :), '--b', mpb_X, mpb_P_E_R(3, :), '-b', ...
%      pb_X, pb_P_E_R(4, :), '--c', mpb_X, mpb_P_E_R(4, :), '-c', ...
%      pb_X, pb_P_E_R(5, :), '--m', mpb_X, mpb_P_E_R(5, :), '-m', ...
%      'LineWidth', 2);
%  
% title(['Potential v. Distance from Interface  ',...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Potential (V)   ', 'FontSize', 16);
% legend('er = 30 (PB)', 'er = 30 (MPB)', 'er = 50 (PB)', ...
%        'er = 50 (MPB)', 'er = 78.3 (PB)', 'er = 78.3 (MPB)', ...
%        'er = 100 (PB)', 'er = 100 (MPB)', 'er = 120 (PB)', ...
%        'er = 120 (MPB)');
% 
% pause;
% 
% % Permittivity | Ion Concentration
% 
% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_E_R(1, :) ./ 1000, '-r', ...
%      pb_X, pb_Cneg_E_R(1, :) ./ 1000, '--r', ...
%      pb_X, pb_Cpos_E_R(2, :) ./ 1000, '-g', ...
%      pb_X, pb_Cneg_E_R(2, :) ./ 1000, '--g', ...
%      pb_X, pb_Cpos_E_R(3, :) ./ 1000, '-b', ...
%      pb_X, pb_Cneg_E_R(3, :) ./ 1000, '--b', ...
%      pb_X, pb_Cpos_E_R(4, :) ./ 1000, '-c', ...
%      pb_X, pb_Cneg_E_R(4, :) ./ 1000, '--c', ...
%      pb_X, pb_Cpos_E_R(5, :) ./ 1000, '-m', ...
%      pb_X, pb_Cneg_E_R(5, :) ./ 1000, '--m', ...
%       'LineWidth', 2,);
%  
% title(['Ion Concentration v. Distance from Interface (PB)   ', ...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('er = 30 (z = +1)', 'er = 30 (z = -1)', 'er = 50 (z = +1)', ...
%        'er = 50 (z = -1)', 'er = 78.3 (z = +1)', 'er = 78.3 (z = -1)', ...
%        'er = 100 (z = +1)', 'er = 100 (z = -1)', 'er = 120 (z = +1)', ...
%        'er = 120 (z = -1)');
% 
% subplot(2, 1, 2);
% plot(mpb_X, mpb_Cpos_E_R(1, :) ./ 1000, '-r', ...
%      mpb_X, mpb_Cneg_E_R(1, :) ./ 1000, '--r', ...
%      mpb_X, mpb_Cpos_E_R(2, :) ./ 1000, '-g', ...
%      mpb_X, mpb_Cneg_E_R(2, :) ./ 1000, '--g', ...
%      mpb_X, mpb_Cpos_E_R(3, :) ./ 1000, '-b', ...
%      mpb_X, mpb_Cneg_E_R(3, :) ./ 1000, '--b', ...
%      mpb_X, mpb_Cpos_E_R(4, :) ./ 1000, '-c', ...
%      mpb_X, mpb_Cneg_E_R(4, :) ./ 1000, '--c', ...
%      mpb_X, mpb_Cpos_E_R(5, :) ./ 1000, '-m', ...
%      mpb_X, mpb_Cneg_E_R(5, :) ./ 1000, '--m', ...
%      'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (MPB)   ', ...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('er = 30 (z = +1)', 'er = 30 (z = -1)', 'er = 50 (z = +1)', ...
%        'er = 50 (z = -1)', 'er = 78.3 (z = +1)', 'er = 78.3 (z = -1)', ...
%        'er = 100 (z = +1)', 'er = 100 (z = -1)', 'er = 120 (z = +1)', ...
%        'er = 120 (z = -1)');


%-------------------------------------------------------------------------
% C. Effective Ion Size
% 
% [pb_X, pb_P_EFF, ~] = pb_potential(P_0, C_0, E_R, Z);
% pb_Cpos_EFF = (C_0 .* (exp((- E / (K * T)) .* pb_P_EFF)));
% pb_Cneg_EFF = (C_0 .* (exp((E / (K * T)) .* pb_P_EFF)));
% 
% 
% mpb_P_EFF = zeros(numel(EFF_options), 301);
% mpb_Cpos_EFF = zeros(numel(EFF_options), 301);
% mpb_Cneg_EFF = zeros(numel(EFF_options), 301);
% 
% for i = 1 : numel(EFF_options)
%     [mpb_X, mpb_P_EFF(i, :), ~] = mpb_potential(P_0, C_0, ...
%         E_R, EFF_options(i), Z);
%     mpb_Cpos_EFF(i, :) = (C_0 .* (exp((- E / (K * T)) .* mpb_P_EFF(i, :))));
%     mpb_Cneg_EFF(i, :) = (C_0 .* (exp((E / (K * T)) .* mpb_P_EFF(i, :))));
% end
% 
% % Ion Size | Potential
% plot(pb_X, pb_P_EFF, '--r', mpb_X, mpb_P_EFF(1, :), '-r', ...
%      mpb_X, mpb_P_EFF(2, :), '-g', mpb_X, mpb_P_EFF(3, :), '-b', ...
%      mpb_X, mpb_P_EFF(4, :), '-c', mpb_X, mpb_P_EFF(5, :), '-m', ...
%      'LineWidth', 2);
%  
% title(['Potential v. Distance from Interface  ',...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, er = 78.3)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Potential (V)   ', 'FontSize', 16);
% legend('PB', 'MPB ion size = 0.1 nm', 'MPB ion size = 0.5 nm', ...
%        'MPB ion size = 1.0 nm', 'MPB ion size = 3.0 nm', 'MPB ion size = 5.0 nm');
% 
% pause;
% 
% % Ion Size | Ion Concentration
% 
% plot(pb_X, pb_Cpos_EFF ./ 1000, '-k', ...
%      pb_X, pb_Cneg_EFF ./ 1000, '--k', ...
%      mpb_X, mpb_Cpos_EFF(1, :) ./ 1000, '-r', ...
%      mpb_X, mpb_Cneg_EFF(1, :) ./ 1000, '--r', ...
%      mpb_X, mpb_Cpos_EFF(2, :) ./ 1000, '-g', ...
%      mpb_X, mpb_Cneg_EFF(2, :) ./ 1000, '--g', ...
%      mpb_X, mpb_Cpos_EFF(3, :) ./ 1000, '-b', ...
%      mpb_X, mpb_Cneg_EFF(3, :) ./ 1000, '--b', ...
%      mpb_X, mpb_Cpos_EFF(4, :) ./ 1000, '-c', ...
%      mpb_X, mpb_Cneg_EFF(4, :) ./ 1000, '--c', ...
%      mpb_X, mpb_Cpos_EFF(5, :) ./ 1000, '-m', ...
%      mpb_X, mpb_Cneg_EFF(5, :) ./ 1000, '--m', ...
%      'LineWidth', 2);
%  
% title(['Ion Concentration v. Distance from Interface (MPB)   ', ...
%     '(z = 1, C0 = 0.15 M, P0 = 25 mV, er = 78.3)   '], 'FontSize', 16);
% xlabel('Distance(m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('PB (z = +1)', 'PB (z = -1)', 'MPB ion size = 0.1 nm (z = +1)', ...
%     'MPB ion size = 0.1 nm (z = -1)', 'MPB ion size = 0.5 nm (z = +1)', ...
%     'MPB ion size = 0.5 nm (z = -1)', 'MPB ion size = 1.0 nm (z = +1)', ...
%     'MPB ion size = 1.0 nm (z = -1)', 'MPB ion size = 3.0 nm (z = +1)', ...
%     'MPB ion size = 3.0 nm (z = -1)', 'MPB ion size = 5.0 nm (z = +1)', ...
%     'MPB ion size = 5.0 nm (z = -1)');


%--------------------------------------------------------------------------
% D. Valence

% [pb_X, pb_P_Z1, ~] = pb_potential(P_0, C_0, E_R, Z_options(1));
% [pb_X, pb_P_Z2, ~] = pb_potential(P_0, C_0, E_R, Z_options(2));
% [mpb_X, mpb_P_Z1, ~] = mpb_potential(P_0, C_0, E_R, EFF, Z_options(1));
% [mpb_X, mpb_P_Z2, ~] = mpb_potential(P_0, C_0, E_R, EFF, Z_options(2));

plot(pb_X, pb_P_Z1, '--r', pb_X, pb_P_Z2, '--b', mpb_X, mpb_P_Z1, '-r', ...
    mpb_X, mpb_P_Z2, '-b', 'LineWidth', 2);
title(['Potential v. Distance from Interface  ',...
    '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '], 'FontSize', 16);
xlabel('Distance (m)   ', 'FontSize', 16);
ylabel('Potential (V)   ', 'FontSize', 16);
legend('z = +/- 1 (PB)', 'z = +/- 2 (PB)', 'z = +/- 1 (MPB)', 'z = +/- 2 (MPB)');

% pause;
% 
% pb_Cpos_Z1 = (C_0 .* (exp((- E / (K * T)) .* pb_P_Z1)));
% pb_Cneg_Z1 = (C_0 .* (exp((E / (K * T)) .* pb_P_Z1)));
% pb_Cpos_Z2 = (C_0 .* (exp((- E / (K * T)) .* pb_P_Z2)));
% pb_Cneg_Z2 = (C_0 .* (exp((E / (K * T)) .* pb_P_Z2)));
% 
% mpb_Cpos_Z1 = (C_0 .* (exp((- E / (K * T)) .* mpb_P_Z1)));
% mpb_Cneg_Z1 = (C_0 .* (exp((E / (K * T)) .* mpb_P_Z1)));
% mpb_Cpos_Z2 = (C_0 .* (exp((- E / (K * T)) .* mpb_P_Z2)));
% mpb_Cneg_Z2 = (C_0 .* (exp((E / (K * T)) .* mpb_P_Z2)));
% 
% subplot(2, 1, 1);
% plot(pb_X, pb_Cpos_Z1 ./ 1000, '-r', pb_X, pb_Cneg_Z1 ./ 1000, '--r', ...
%      pb_X, pb_Cpos_Z2 ./ 1000, '-b', pb_X, pb_Cneg_Z2 ./ 1000, '--b');
% title(['Ion Concentration v. Distance from Interface (PB)  ',...
%     '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('z = +1', 'z = -1', 'z = +2', 'z = -2');
% 
% subplot(2, 1, 2);
% plot(mpb_X, mpb_Cpos_Z1 ./ 1000, '-r', mpb_X, mpb_Cneg_Z1 ./ 1000, '--r', ...
%      mpb_X, mpb_Cpos_Z2 ./ 1000, '-b', mpb_X, mpb_Cneg_Z2 ./ 1000, '--b', ...
%      'LineWidth', 2);
% title(['Ion Concentration v. Distance from Interface (MPB)  ',...
%     '(C0 = 0.15 M, P0 = 25 mV, er = 78.3 ion size = 1 nm)   '], 'FontSize', 16);
% xlabel('Distance (m)   ', 'FontSize', 16);
% ylabel('Ion Concentration (M)   ', 'FontSize', 16);
% legend('z = +1', 'z = -1', 'z = +2', 'z = -2');
